### ISSUE TITLE
I can't use 'cwtft' function 

### ISSUE THREAD

**Issue by minDyong** [peterhcharlton/RRest#10]
I followed your guide video in Youtube but I got a problem during run this algorithm.

[Wfm.m]

%% CWT
% Specify characteristics
s0  = 6/d_s.fs;  % smallest scale
ds = 0.001; % spacing between scales
NbSc = 3000; % number of scales
SCA = {s0,ds,NbSc, 'lin'}; % specify scales
cwtstruct = cwtft({d_s.v, 1/d_s.fs},'scales',SCA);

When this function run, it turns out it can not input cell type parameter.
But when I searched the function of 'cwftf', the document tells me, 
the input arguments can be a vector, a structure array, or a cell array.
[https://kr.mathworks.com/help/wavelet/ref/cwtft.html]

How should I run this algorithm perfectly???

My matlab version is R2018a and I have a Wavelet toolbox license

**Comment by peterhcharlton** [comment]
Hello,

Thanks for your comment. I've had a quick look at the [Matlab help](https://uk.mathworks.com/help/wavelet/ref/cwtft.html), and it says that the "cwtft" function is no longer recommended, and that one should use the ["cwt" function](https://uk.mathworks.com/help/wavelet/ref/cwt.html) instead. I would suggest trying this.

I will try to incorporate an update to fix the problem in the next release.

Best wishes,

Pete

**Comment by peterhcharlton** [comment]
In the meantime, if you wish to carry on using the scripts without the Wavelet-based methods then I'd recommend omitting these methods from the analysis. There are instructions on how to do this [here](https://github.com/peterhcharlton/RRest/wiki/Universal-Parameters)

**Comment by minDyong** [comment]
Followed the instruction, I removed function that using cwt, it finally run properly. Thanks !!
