### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by lzdh** [peterhcharlton/RRest#18]
Hi Peter,

I just wonder is there a python version for RRest?

Many thanks,
Jessie

**Comment by PeterGamma** [comment]
Yes, a Python version would be great. Many programmers say, you can easily do without Matlab, and that Matlab is not worth buying. Matlab Home is about 200 USD, but you are not allowed to publish with it. Who wants to spend 2000 USD for Matlab Standard edition for a respiratory rate estimation? Matlab is furthermore difficult for mobile applications. It does not run on Rasperri Pi, Linux Phones or Linux Watches. Python even runs on the Adafruit Clue Chip (MicroPython). Python is a great alternative to Matlab.

**Comment by peterhcharlton** [comment]
Thank you for these comments. I agree it would be great to have a Python version. At present we don't have anyone to undertake the work of translating the algorithms from Matlab into Python. If anyone is interested in contributing then do let me know.
