### ISSUE TITLE
Automating the file separator

### ISSUE THREAD

**Issue by rcasero** [peterhcharlton/RRest#4]
As a small thing, the file separator doesn't need to be hard coded by the user here

https://github.com/peterhcharlton/RRest/blob/31aaaadc4f7a1f12450b6e3b6e5aaa6ffae9b7e0/RRest_v3.0/Algorithms/setup_universal_params.m#L48

if you change the line to

`up.paths.slash_direction = filesep;`

**Comment by peterhcharlton** [comment]
Many thanks indeed for pointing this out - it's very helpful. I'll include the change in the next version.

Best wishes,

Pete
